### ISSUE TITLE
Too little thumbnails

### ISSUE THREAD

**Issue by toptierlabs** [itsmeichigo/ICGVideoTrimmer#7]
I have a 8 minutes video, and my maximum trim size is 40 seconds. However I am seeing too little thumbnails to trim correctly. I am getting 1 thumb per each 30 seconds. I have tried to change thumbwidth but it doesn't change it.

Any ideas?

**Comment by itsmeichigo** [comment]
Hi, sorry for the late response.

The reason for your issue is that the max length is too small causing the image generator to get thumbnails for your video frequently. However, due to the video's frame rate, some of the requested times are considered the same frame. Please refer to this [SO answer](http://stackoverflow.com/a/11758811) if you're still confused.

Thanks.
